version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: url_shortener_db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: kerem
      POSTGRES_PASSWORD: kerem
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kerem -d url_shortener"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
